[project]
name = "hidrogel-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "importnb>=2023.11.1",
    "ipykernel>=7.3.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.3",
    "opencv-python>=4.13.0.92",
    "openpiv>=0.25.4",
    "pandas>=3.0.1",
    "pims>=0.7",
    "scikit-image>=0.26.0",
    "seaborn>=0.13.2",
    "tifffile>=2026.3.3",
    "tqdm>=4.67.3",
    "trackpy>=0.7",
]
